repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
        entry: sh -c 'cd backend && poetry check'
        
      # - id: poetry-lock
      #   entry: sh -c 'cd backend && poetry lock'
        
      - id: poetry-check
        entry: sh -c 'cd aws_write && poetry check'
        
      # - id: poetry-lock
      #   entry: sh -c 'cd aws_write && poetry lock'
        
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.14.2
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]