CSV_FILE_NAME = "data.csv"
CSV_FILE_PATH = f"./backend/{CSV_FILE_NAME}"
TENSORBOARD_LOG = "runs/user_experiment"
ONNX_MODEL = "my_deep_learning_model.onnx"
LOSS_VIZ = "visualization/my_loss_plot.png"
TRAIN_TIME_CSV = "epoch_times.csv"
NETRON_URL = "https://netron.app/"
OPEN_FILE_BUTTON = "open-file-button"