def test_all_imports():
  import backend.aws_helpers.dynamo_db_utils.base_db
  import backend.aws_helpers.dynamo_db_utils.status_db
  import backend.common.constants
  import backend.common.dataset
  import backend.common.default_datasets
  import backend.common.email_notifier
  import backend.common.loss_functions
  import backend.common.optimizer
  import backend.common.utils
  import backend.dl.dl_eval
  import backend.dl.dl_model
  import backend.dl.dl_model_parser
  import backend.dl.dl_trainer
  import backend.dl.pretrained
  import backend.ml.ml_trainer