openapi: "3.0.0"
info:
  title: DLP API
  description: API endpoints for the Deep Learning Playground Project
  version: "1.0.0"
paths:
  /api/s3/getSignedUploadUrl:
    post:
      description: Endpoint to upload files to S3
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - version
                - filename
                - file
              properties:
                version:
                  type: integer
                  description: The file version
                filename:
                  type: string
                  description: The name of the file
                file:
                  type: object
                  description: the file
              example:
                version: 2
                filename: "file"
                file: { "col1": [val1, val2], "col2": [val3, val4] }
        required: true
      responses:
        "200":
          description: Data uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Upload successful"
        "400":
          description: Upload didn't go through successfully. This is usually something wrong with your code
        "401":
          description: User is not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User is not authenticated"
  /api/s3/getExecutionsFilesPresignedUrls:
    post:
      description: API Endpoint to use S3 Presigned URLs to retrieve result files from S3 given an execution id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - exec_id
              properties:
                exec_id:
                  type: string
                  description: The execution id
              example:
                exec_id: '1234'
        required: true
      responses:
        "200":
          description: Result files for your execution fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Result file fetch successful"
        "400":
          description: Result file fetch didn't go through successfully. This is usually something wrong with your code
        "401":
          description: User is not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User is not authenticated"
  /api/s3/getUserDatasetFilesData:
    post: 
      description: API Endpoint to retrieve all user dataset files uploaded in S3
      requestBody:
        content:
          application/json:
            schema:
              type: object 
              required: 
                - uid
                - data_source 
              properties:
                uid: 
                  type: string 
                  description: User ID 
                data_source: 
                  type: string 
                  description: 'What type of training was the user running (eg: TABULAR, PRETRAINED, OBJECT_DETECTION, IMAGE, etc)'
      responses:
        "200":
          description: User Dataset files for user fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User Dataset file fetch successful"
        "400":
          description: User Dataset files for user wasn't fetched successfully. This is usually something wrong with your code
        "401":
          description: User is not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User is not authenticated"
