openapi: "3.0.0"
info:
  title: DLP API
  description: API endpoints for the Deep Learning Playground Project
  version: "1.0.0"
paths:
  /api/object-detection:
    post:
      description: Endpoint to detect objects on user uploaded images
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - problem_type
                - detection_type
                - transforms
              properties:
                problem_type:
                  type: string
                  description: problem type selected (Labels, Celebrities)
                detection_type:
                  type: string
                  description: detection type selected (Rekognition, Huggingface)
                transforms:
                  type: array
                  description: transforms to be applied to the image
              example:
                problem_type: "Labels"
                detection_type: "Rekognition"
                transforms: [val1, val2, val3]
        required: true
      responses:
        "200":
          description: Objects detected successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Detection worked successfully"
                  dl_results:
                    type: object
                    example: { "col1": [val1, val2], "col2": [val3, val4] }
                  auxiliary_outputs:
                    type: array
                    example: [val1, val2, val3]
        "400":
          description: Detection didn't go through successfully. This is usually something wrong with your code
        "401":
          description: User is not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User is not authenticated"
