openapi: "3.0.0"
info:
  title: DLP API
  description: API endpoints for the Deep Learning Playground Project
  version: "1.0.0"
paths:
  /api/sendUserCodeEval:
    post:
      description: Given user inputted code in the preprocessing mode, execute it!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - data
                - codeSnippet
              properties:
                data:
                  type: object
                  description: The email address of the recipient
                codeSnippet:
                  type: string
                  description: The subject of the email
              example:
                data: { "col1": [val1, val2], "col2": [val3, val4] }
                codeSnippet: 'def preprocess(df):print("Hello World")'
        required: true
      responses:
        "200":
          description: Preprocessed data successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Preprocessed data"
                  data:
                    type: object
                    example: { "col1": [val1, val2], "col2": [val3, val4] }
                  columns:
                    type: array
                    example: ["newcol1"]
        "400":
          description: Preprocess didn't go through successfully. This is usually something wrong with your code
        "401":
          description: User is not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User is not authenticated"
