openapi: '3.0.0'
info:
  title: DLP API 
  description: API endpoints for the Deep Learning Playground Project
  version: '1.0.0'
paths:
  /test:
    get:
      summary: A simple endpoint to test if our backend is alive
      responses:
        '200':
          description: Test Backend alive
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: string 
                    example: "Backend is alive"