openapi: "3.0.0"
info:
  title: DLP API
  description: API endpoints for the Deep Learning Playground Project
  version: "1.0.0"
paths:
  /api/upload:
    post:
      description: Endpoint to upload files locally
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: object
                  description: the file
              example:
                file: { "col1": [val1, val2], "col2": [val3, val4] }
        required: true
      responses:
        "200":
          description: Data uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Upload success"
        "400":
          description: Upload didn't go through successfully. This is usually something wrong with your code
        "401":
          description: User is not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User is not authenticated"
