openapi: "3.0.0"
info:
  title: DLP API
  description: API endpoints for the Deep Learning Playground Project
  version: "1.0.0"
paths:
  /api/writeToQueue:
    post:
      description: Endpoint to add training requests to SQS queue
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - queue_data
              properties:
                queue_data:
                  type: object
                  description: data to be added to queue
              example:
                queue_data: { "col1": [val1, val2], "col2": [val3, val4] }
        required: true
      responses:
        "200":
          description: Wrote to queue successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Successfully added your training request to the queue"
        "400":
          description: Write to queue didn't go through successfully. This is usually something wrong with your code
        "401":
          description: User is not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User is not authenticated"
