name: "🤖 Sweep: Refactor"
title: "Sweep: "
description: Sweep-automated refactor request
labels: ["sweep"]
body:
  - type: markdown
    attributes:
      value: |
        👋 Hello there. This is a refactor issue that will use Sweep's AI to automatically write code and resolve this issue.

        ---

        The title must start with "Sweep: " and you can write something like 
        - "Sweep: Modify the ... api endpoint to use ... version and ... framework"

        Include as much information/detail on the proposal. You may also build on top of another non-sweep refactor request 👍
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: We are migrating this function to ... version because ...
