name: '🤖 Sweep: Bugfix'
title: 'Sweep: '
description: Sweep-automated bugfix request
labels: ["sweep"]
body:
  - type: markdown
    attributes:
      value: |
        👋 Hello there. This is a bugfix issue that will use Sweep's AI to automatically write code and resolve this issue.

        ---

        The title must start with "Sweep: " and you can write something like 
        - "Sweep: We notice ... behavior when ... happens instead of ..."

        Include as much information/detail on the proposal. You may also build on top of another non-sweep bugfix 👍
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details about the bug
      placeholder: The bug might be in ... file
