name: dlplayground
channels:
  - conda-forge
  - defaults
dependencies:
  - flake8
  - jupyter
  - matplotlib
  - seaborn
  - mypy
  - numpy
  - pytest
  - python=3.9
  - pandas
  - boto3
  - pyyaml
  - pip
  - statsmodels
  - pytorch
  - selenium
  - sendgrid
  - black
  - flask
  - flask-cors
  - flask-socketio
  - ruamel.yaml
  - eventlet
  - pip:
     - torchvision
     - scikit-learn
     - timm
     - wwf
     - fastai==2.7.4