name: dlplayground
channels:
  - conda-forge
  - defaults
dependencies:
  - libgcc
  - scipy.optimize
  - flake8
  - jupyter
  - matplotlib
  - seaborn
  - mypy
  - numpy
  - pytest
  - python=3.9
  - pandas
  - scikit-learn
  - boto3
  - pyyaml
  - pip
  - statsmodels
  - pytorch
  - selenium
  - sendgrid
  - black
  - flask
  - flask-cors
  - ruamel.yaml
  - pip:
     - torchvision
     - timm
     - wwf
     - fastai==2.7.4