name: dlplayground
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp
  - flake8
  - jupyter
  - matplotlib
  - seaborn
  - mypy
  - numpy
  - pytest
  - python=3.9
  - pandas
  - scikit-learn
  - scipy=1.7.3
  - boto3
  - pyyaml
  - pip
  - statsmodels
  - pytorch
  - black
  - flask=2.2.3
  - flask-cors
  - flask-socketio
  - ruamel.yaml
  - eventlet
  - python-dotenv
  - transformers
  - pre-commit
  - pip:
      - torchvision
      - timm
      - wwf
      - fastai==2.7.4
      - firebase_admin
      - pyrebase4
      - moto
      - docker
      - ggshield
