version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: mamba run --live-stream -n dlp gunicorn training.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/training/
    expose:
      - 8000
    # env_file:
    #   - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
