version: '3.8'

services:
  web:
    build: .
    command: mamba run --live-stream -n dlp gunicorn training.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/training/
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env.prod
