version: "3.8"

services:
  web:
    build:
      context: .
      target: production
    volumes:
      - $HOME/.aws:/home/app/.aws:ro
    ports:
      - 8000:8000
    environment:
      - AWS_PROFILE=$AWS_PROFILE
