name: Update Frontend/Backend
on:
  push:
    branches:
      - "action"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3        
    - name: Update frontend
      with:
        ref: frontend
      run: |
        git config --global user.name ${{ secrets.DLP_HELPER_USERNAME }}
        git config --global user.email ${{ secrets.DLP_HELPER_EMAIL}}
        git pull origin main
        git push 
    - name: Update backend-dev
      with:
        ref: backend-dev
      run: |
        git config --global user.name ${{ secrets.DLP_HELPER_USERNAME }}
        git config --global user.email ${{ secrets.DLP_HELPER_EMAIL}}
        git pull origin main
        git push
