name: Format Python Code with Black

on: [pull_request]

jobs:
  linter_name:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.action_black.outputs.is_formatted == 'true'
        with:
          commit_message: ":art: Format Python code with psf/black"
          commit_options: "--no-verify"
          commit_user_name: github-actions
          commit_user_email: ghaction@github.com
