name: Poetry Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6

      - name: Check Poetry in backend directory
        run: |
          cd backend
          poetry check
          poetry check

      - name: Check Poetry in aws_write directory
        run: |
          cd aws_write
          poetry check
   