name: Depcheck

on:
  push:
    branches:
      - nextjs
  pull_request:
    branches:
      - nextjs

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install depcheck
        run: yarn global add depcheck

      - name: Run depcheck
        run: depcheck ./frontend --fail-on-error