name: Frontend Workflow Check
on: [pull_request, push]

concurrency: preview-${{ github.ref }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm 
        working-directory: ./frontend

      - name: Install
        run: pnpm install --frozen-lockfile
        id: install
        working-directory: ./frontend


      - name: Run ESLint
        run: pnpm run lint
        working-directory: ./frontend

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm 
        working-directory: ./frontend

      - name: Install
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend

      - name: Test
        run: echo "pnpm run test should be here"
        working-directory: ./frontend
    
    