name: Frontend Workflow Check
on: [pull_request, push]

concurrency: preview-${{ github.ref }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm 
        working-directory: ./frontend

      - name: Install
        run: pnpm install --frozen-lockfile
        id: install
        working-directory: ./frontend


      - name: Run ESLint
        run: pnpm run lint
        working-directory: ./frontend

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install pnpm
        run: npm install -g pnpm 
        working-directory: ./frontend

      - name: Install
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend

      - name: Build
        run: pnpm build
        env:
          REACT_APP_CAPTCHA_SITE_KEY: ${{ secrets.REACT_APP_CAPTCHA_SITE_KEY }}
          REACT_APP_FEEDBACK_EMAIL: ${{ secrets.REACT_APP_FEEDBACK_EMAIL }}
        working-directory: ./frontend
