name: Python Package (Poetry)

on:
  push:
    branches:
      - main
      - prod-deploy
      - poetry-setup
  pull_request:
    paths:
      - "backend/**"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          source $HOME/.poetry/env
      - name: Install dependencies
        run: poetry install
      - name: Formatting Fixes
        run: poetry shell && poetry run black ./
      - name: Test with pytest
        run: poetry shell && pytest tests
