name: Python Package using Conda

on:
  push:
    branches:
      - "main"
      - "prod-deploy"
  pull_request:
    types:
      - "opened"
      - "synchronize"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        cd conda && ls
        ls
        conda env update -f environment.yml
        conda init bash
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate dlplayground
    - name: Formatting Fixes
      run: |
        conda init bash
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate dlplayground
        black ./
    - name: Check that requirements.txt exists
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "requirements.txt"
        
    - name: Automatic requirements.txt for Python Projects
      if: steps.check_files.outputs.files_exists == 'false'
      run: |
        conda init bash
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate dlplayground
        python ./yml_to_req.py
        git config --global user.name ${{ secrets.DLP_HELPER_USERNAME }}
        git config --global user.email ${{ secrets.DLP_HELPER_EMAIL}}
        git add requirements.txt
        git commit -m "generating requirements.txt"
        git push
    - name: Test with pytest
      run: |
        conda init bash
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate dlplayground
        ls
        pytest tests
