name: Automatic requirements.txt generation

# Only trigger, when the build succeeded
on:
  workflow_run:
    workflows: ["Python Package using Conda"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        uses: ryan-rozario/pipreqs-action-cpy@master

        # Put an example of mandatory inputs here
        with:
          PROJECT_PATH:   #default is the root of the repository
          REQUIREMENT_PATH:  #default is requirement.txt in the root of your repository 