name: Update Frontend/Backend/FullStack
on:
  push:
    branches:
      - "main"

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: PR from main to frontend
      uses: tretuna/sync-branches@1.4.0
      id: frontend
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FROM_BRANCH: "main"
        TO_BRANCH: "frontend"

    - name: PR from main to backend
      uses: tretuna/sync-branches@1.4.0
      id: backend
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FROM_BRANCH: "main"
        TO_BRANCH: "backend"

    - name: PR from main to full-stack
      uses: tretuna/sync-branches@1.4.0
      id: full_stack
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FROM_BRANCH: "main"
        TO_BRANCH: "full-stack"

    - name: approve frontend PR
      uses: hmarr/auto-approve-action@v2.4.0
      with:
        pull-request-number: ${{ steps.frontend.outputs.PULL_REQUEST_NUMBER }}
        github-token: ${{ secrets.GH_PAT }}
    
    - name: approve backend PR
      uses: hmarr/auto-approve-action@v2.4.0
      with:
        pull-request-number: ${{ steps.backend.outputs.PULL_REQUEST_NUMBER }}
        github-token: ${{ secrets.GH_PAT }}

    - name: approve full-stack PR
      uses: hmarr/auto-approve-action@v2.4.0
      with:
        pull-request-number: ${{ steps.full_stack.outputs.PULL_REQUEST_NUMBER }}
        github-token: ${{ secrets.GH_PAT }}

    - name: merge frontend PR
      uses: pascalgn/automerge-action@v0.15.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST: ${{ steps.frontend.outputs.PULL_REQUEST_NUMBER }}
        MERGE_LABELS: ""
        MERGE_RETRY_SLEEP: 60000
        MERGE_RETRIES: 15

    - name: merge backend PR
      uses: pascalgn/automerge-action@v0.15.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST: ${{ steps.backend.outputs.PULL_REQUEST_NUMBER }}
        MERGE_LABELS: ""
        MERGE_RETRY_SLEEP: 60000
        MERGE_RETRIES: 15

    - name: merge full-stack PR
      uses: pascalgn/automerge-action@v0.15.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST: ${{ steps.full_stack.outputs.PULL_REQUEST_NUMBER }}
        MERGE_LABELS: ""
        MERGE_RETRY_SLEEP: 60000
        MERGE_RETRIES: 15