name: Update Frontend/Backend
on:
  push:
    branches:
      - "action"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update frontend and backend-dev
      run: |
        git config user.name ${{ secrets.DLP_HELPER_USERNAME }}
        git config user.email ${{ secrets.DLP_HELPER_EMAIL}}
        git fetch --all
        git switch f2
        git pull --ff-only origin main
        git push
        git switch b2
        git pull --ff-only origin main
        git push
        