name: Deploy to Vercel
on:
  push:
    branches: [main]
  pull_request:
    types: [labeled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check label or branch
        id: checker
        run: echo ::set-output name=to_run::${{ ((github.event.label.name == 'deploy') || (github.ref == 'refs/heads/main')) && 'True' || 'False' }}
    outputs:
      status: ${{ steps.checker.outputs.to_run }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'True'
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment
        id: environment
        run: echo ::set-output name=environment::${{ github.event.label.name == 'deploy' && 'Development' || 'Preview' }}

      - name: Remove Label
        uses: andymckay/labeler@master
        with:
          remove-labels: 'deploy'

      - name: PR Comment
        run: |
          echo "\
            Github Ref: ${{ github.ref }}  \
            PR: ${{ github.event.label.name }}  \
            Environment: ${{ steps.environment.outputs.environment }}  \
          "
